# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MimiRemote < Formula
  desc "iPad companion agent for user-owned Mac developer environments"
  homepage "https://github.com/gaixianggeng/mimi-remote"
  version "0.3.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.3.9/mimi-remote_0.3.9_darwin_amd64.tar.gz"
      sha256 "0160d05321fef9da17ad565d76fab545072e3e81f4463b7bcc1db8f38921ff85"

      define_method(:install) do
        bin.install "agentd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.3.9/mimi-remote_0.3.9_darwin_arm64.tar.gz"
      sha256 "99e02e3adf26ac01a42509bae93dadc26b08f30a97ecde8ac12d9023d8f2551c"

      define_method(:install) do
        bin.install "agentd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.3.9/mimi-remote_0.3.9_linux_amd64.tar.gz"
      sha256 "9e16b2c565721c67bf5bcbe09b7dad562545fc396e86f074c0a5ec7722ac0f7f"
      define_method(:install) do
        bin.install "agentd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.3.9/mimi-remote_0.3.9_linux_arm64.tar.gz"
      sha256 "acf5a79c79cbf7f40e889e61cf4f0fc76f1fe3c1221dce6c6d0e878fa86f5089"
      define_method(:install) do
        bin.install "agentd"
      end
    end
  end

  service do
    run [opt_bin/"agentd", "serve"]
    environment_variables PATH: std_service_path_env
    keep_alive true
    log_path var/"log/mimi-remote.log"
    error_log_path var/"log/mimi-remote.log"
  end

  def caveats
    <<~EOS
      首次使用：
        codex --version
        codex app-server --help
        agentd up

      Mimi Remote App 优先扫描 agentd up 输出的二维码；二维码过期后运行 agentd pair 刷新。
      排障：
        agentd status
        agentd doctor --fix
        agentd logs
    EOS
  end

  test do
    system "#{bin}/agentd", "version"
  end
end
