# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MimiRemote < Formula
  desc "iPad companion agent for user-owned Mac developer environments"
  homepage "https://github.com/gaixianggeng/codex-ipad-agent"
  version "0.2.13"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gaixianggeng/codex-ipad-agent/releases/download/v0.2.13/mimi-remote_0.2.13_darwin_amd64.tar.gz"
      sha256 "ce3a16ad9e8e94e465ab75a1c19db5786c8a765cf54845146590d569b22a1cd6"

      define_method(:install) do
        bin.install "agentd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gaixianggeng/codex-ipad-agent/releases/download/v0.2.13/mimi-remote_0.2.13_darwin_arm64.tar.gz"
      sha256 "d5f0f34a6a66bd93e6646cc4629fb91c6438e18d3eb18a213f0e82da0853c02c"

      define_method(:install) do
        bin.install "agentd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gaixianggeng/codex-ipad-agent/releases/download/v0.2.13/mimi-remote_0.2.13_linux_amd64.tar.gz"
      sha256 "926127bbfcf9d813b1e3ab19c048322046382b7ad3d72527af793bcd65a316e5"
      define_method(:install) do
        bin.install "agentd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gaixianggeng/codex-ipad-agent/releases/download/v0.2.13/mimi-remote_0.2.13_linux_arm64.tar.gz"
      sha256 "df0b765292f09a4c3502eb2368968b457d554be9a66201328ee1aa64ed1bbfa2"
      define_method(:install) do
        bin.install "agentd"
      end
    end
  end

  service do
    run [opt_bin/"agentd", "serve"]
    environment_variables PATH: std_service_path_env
    keep_alive true
    log_path var/"log/mimi-remote.log"
    error_log_path var/"log/mimi-remote.log"
  end

  def caveats
    <<~EOS
      首次使用：
        codex --version
        codex app-server --help
        agentd up

      Mimi Remote App 优先扫描 agentd up 输出的二维码；二维码过期后运行 agentd pair 刷新。
      排障：
        agentd status
        agentd doctor --fix
        agentd logs
    EOS
  end

  test do
    system "#{bin}/agentd", "version"
  end
end
