# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MimiRemote < Formula
  desc "iPad companion agent for user-owned Mac developer environments"
  homepage "https://github.com/gaixianggeng/mimi-remote"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.2.2/mimi-remote_0.2.2_darwin_amd64.tar.gz"
      sha256 "0e1c00970a1cd2f787b71777a55a5661579503e6183786e18b7baf2f079bfcc0"

      define_method(:install) do
        bin.install "agentd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.2.2/mimi-remote_0.2.2_darwin_arm64.tar.gz"
      sha256 "d06cbe46f16087d7b95f1f8728eb18b4e72ce377700979fe5adc5673b152470a"

      define_method(:install) do
        bin.install "agentd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.2.2/mimi-remote_0.2.2_linux_amd64.tar.gz"
      sha256 "aed1aac2f3ee9770f8e4b1f3b0e2ba2e15e3b6c65ffff0ecfa58cb8ef52b5b6c"
      define_method(:install) do
        bin.install "agentd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gaixianggeng/mimi-remote/releases/download/v0.2.2/mimi-remote_0.2.2_linux_arm64.tar.gz"
      sha256 "03aca046abb99f9fb5140ed26dc9fdd9e9eacf9000f3d80e93b69f422e46a978"
      define_method(:install) do
        bin.install "agentd"
      end
    end
  end

  service do
    run [opt_bin/"agentd", "serve"]
    environment_variables PATH: std_service_path_env
    keep_alive true
    log_path var/"log/mimi-remote.log"
    error_log_path var/"log/mimi-remote.log"
  end

  def caveats
    <<~EOS
      首次使用：
        codex --version
        codex app-server --help
        agentd up

      Mimi Remote App 优先扫描 agentd up 输出的二维码；二维码过期后运行 agentd pair 刷新。
      排障：
        agentd status
        agentd doctor --fix
        agentd logs
    EOS
  end

  test do
    system "#{bin}/agentd", "version"
  end
end
